name: build-native-win-hadoop-libs
run-name: Binaries for hadoop release ${{ github.ref_name }}
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
jobs:
  build-native-libs:
    runs-on: windows-latest
    steps:
      - run: git config --system core.longpaths true
      - uses: actions/checkout@v4
        with:
          repository: apache/hadoop
          ref: ${{ github.ref_name }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
#      - uses: microsoft/setup-msbuild@v1
#      - name: Setup VS Dev Environment
#        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Pre debug output
      - run: |
          msbuild /version
          mvn -v
          gci env:* | sort-object name
          echo "Ref name: $env:GITHUB_REF_NAME"
          echo "Repo: $env:GITHUB_REPOSITORY"
          echo "Workspace dir: $env:GITHUB_WORKSPACE"
      - run: "pwd"
#      - run: mvn dependency:resolve
#      - run: devenv
#      - run: "mvn install -Pdist -DskipTests '-Dmaven.javadoc.skip=true' -pl :hadoop-maven-plugins"
      - name: Run native build
        run: "mvn package '-Pnative-win' -DskipTests '-Dmaven.javadoc.skip=true' -pl ':hadoop-common,:hadoop-maven-plugins'"
        continue-on-error: false
      - name: Package release data
        run: |
          cd "$env:GITHUB_WORKSPACE\hadoop-common-project\hadoop-common\target"
          Compress-Archive -Path .\bin -DestinationPath "$env:GITHUB_WORKSPACE\hadoop-win-utils.zip"
      - name: Create release (gh cmd)
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        run: |
          gh release create -R "$env:GITHUB_REPOSITORY" -n "Windows binaries for hadoop release $env:GITHUB_REF_NAME" -t "$env:GITHUB_REF_NAME" --verify-tag "$env:GITHUB_REF_NAME" "$env:GITHUB_WORKSPACE\hadoop-win-utils.zip"