name: build-native-win-hadoop-libs
run-name: Binaries for hadoop release ${{ github.ref_name }}
#on:
#  push:
#    tags:
#      - "**"

on:
  push:
    branches:
      - main
      - dev

#  workflow_dispatch:
jobs:
  build-native-libs:
    runs-on: windows-latest
    steps:
      - run: git config --system core.longpaths true
      - name: Checkout hadoop repo
        uses: actions/checkout@v5
        with:
          # https://github.com/actions/checkout
          repository: apache/hadoop
          path: hadoop
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Pre debug output
        run: |
          msbuild /version
          mvn -v
          gci env:* | sort-object name
          echo "Ref name: $env:GITHUB_REF_NAME"
          echo "Repo: $env:GITHUB_REPOSITORY"
          echo "Workspace dir: $env:GITHUB_WORKSPACE"
      - run: "pwd"
      - name: Run native build
        # run: "mvn package '-Pnative-win' -DskipTests '-Dmaven.javadoc.skip=true' -pl ':hadoop-common,:hadoop-maven-plugins'"
        run: |
          cd hadoop
          "mvn clean package -Dhttps.protocols=TLSv1.2 -DskipTests -DskipDocs -Pnative-win,dist -Dskip.platformToolsetDetection -Drequire.openssl -Drequire.test.libhadoop -Pyarn-ui -Dtar -Dwindows.cmake.build.type=RelWithDebInfo -Dwindows.build.hdfspp.dll=off -Dwindows.no.sasl=on -Duse.platformToolsetVersion=v142"
        # run: "mvn clean package -Dhttps.protocols=TLSv1.2 -DskipTests -DskipDocs -Pnative-win,dist -Dskip.platformToolsetDetection -Drequire.openssl -Drequire.test.libhadoop -Pyarn-ui -Dshell-executable=C:\Git\bin\bash.exe -Dtar -Dopenssl.prefix=C:\vcpkg\installed\x64-windows -Dcmake.prefix.path=C:\vcpkg\installed\x64-windows -Dwindows.cmake.toolchain.file=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -Dwindows.cmake.build.type=RelWithDebInfo -Dwindows.build.hdfspp.dll=off -Dwindows.no.sasl=on -Duse.platformToolsetVersion=v142"
        continue-on-error: false
      - name: Package release data
        run: |
          cd "$env:GITHUB_WORKSPACE\hadoop-common-project\hadoop-common\target"
          Compress-Archive -Path .\bin -DestinationPath "$env:GITHUB_WORKSPACE\hadoop-win-utils.zip"
      - name: Create release (gh cmd)
        if: ${{ startsWith(github.ref_name, 'rel/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        run: |
          gh release create --latest -R "$env:GITHUB_REPOSITORY" -n "Windows binaries for hadoop release $env:GITHUB_REF_NAME" -t "$env:GITHUB_REF_NAME" --verify-tag "$env:GITHUB_REF_NAME" "$env:GITHUB_WORKSPACE\hadoop-win-utils.zip"
      - name: Create pre-release (gh cmd)
        if: ${{ !startsWith(github.ref_name, 'rel/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        run: |
          gh release create -p -R "$env:GITHUB_REPOSITORY" -n "Windows binaries for hadoop release $env:GITHUB_REF_NAME" -t "$env:GITHUB_REF_NAME" --verify-tag "$env:GITHUB_REF_NAME" "$env:GITHUB_WORKSPACE\hadoop-win-utils.zip"
