name: build-native-win-hadoop-libs
run-name: Binaries for hadoop release ${{ github.ref_name }}
on: [push]
jobs:
  build-native-libs:
    runs-on: windows-latest
    steps:
      - run: git config --system core.longpaths true
      - uses: actions/checkout@v4
        with:
          repository: apache/hadoop
          ref: ${{ github.ref_name }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#      - uses: microsoft/setup-msbuild@v1
#      - name: Setup VS Dev Environment
#        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: msbuild /version
      - run: mvn -v
      - run: gci env:* | sort-object name
      - run: "pwd"
#      - run: mvn dependency:resolve
#      - run: devenv
#      - run: "mvn install -Pdist -DskipTests '-Dmaven.javadoc.skip=true' -pl :hadoop-maven-plugins"
      - name: Run native build
        run: "mvn package '-Pnative-win' -DskipTests '-Dmaven.javadoc.skip=true' -pl ':hadoop-common,:hadoop-maven-plugins'"
        continue-on-error: false
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: generated-binaries
          path: D:\a\hadoop-native-win-libs\hadoop-native-win-libs\hadoop-common-project\hadoop-common\target/bin
          retention-days: 5
