name: build-native-win-hadoop-libs
run-name: Binaries for hadoop release ${{ github.ref_name }}
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
jobs:
  build-native-libs:
    runs-on: windows-latest
    steps:
      - run: git config --system core.longpaths true
      - uses: actions/checkout@v4
        with:
          repository: apache/hadoop
          ref: ${{ github.ref_name }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
#      - uses: microsoft/setup-msbuild@v1
#      - name: Setup VS Dev Environment
#        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: msbuild /version
      - run: mvn -v
      - run: gci env:* | sort-object name
      - run: "pwd"
#      - run: mvn dependency:resolve
#      - run: devenv
#      - run: "mvn install -Pdist -DskipTests '-Dmaven.javadoc.skip=true' -pl :hadoop-maven-plugins"
      - name: Run native build
        run: "mvn package '-Pnative-win' -DskipTests '-Dmaven.javadoc.skip=true' -pl ':hadoop-common,:hadoop-maven-plugins'"
        continue-on-error: false
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: generated-binaries
          path: D:\a\hadoop-native-win-libs\hadoop-native-win-libs\hadoop-common-project\hadoop-common\target/bin
          retention-days: 5
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          # TODO: set prerelease for non rel/ tags
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: Windows binaries (hadoop.dll and winutils.exe) for hadoop release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
      - name: upload windows artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\hadoop-native-win-libs\hadoop-native-win-libs\hadoop-common-project\hadoop-common\target/bin
          asset_name: hadoop-winutils.zip
          asset_content_type: application/zip