name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-native-libs:
    runs-on: windows-latest
    steps:
      - run: git config --system core.longpaths true
      - uses: actions/checkout@v4
        with:
          repository: apache/hadoop
          ref: branch-3.3
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - uses: microsoft/setup-msbuild@v1
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - run: msbuild /version
      - run: mvn -v
      - run: gci env:* | sort-object name
      - run: "pwd"
#      - run: devenv
#      - run: "mvn install -Pdist -DskipTests '-Dmaven.javadoc.skip=true' -pl :hadoop-maven-plugins"
      - run: "mvn package '-Pdist,native-win' -DskipTests '-Dmaven.javadoc.skip=true' -pl ':hadoop-common,:hadoop-maven-plugins'"
