name: check-for-release
run-name: Checking if there is a new hadoop release
on: [push]
#  schedule:
#    - cron: "0 6 * * *"
jobs:
  check-for-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          path: checker
      - uses: actions/checkout@v4
        with:
          repository: apache/hadoop
          path: hadoop
      - name: Fetch release version
        run: |
          cd hadoop
          git tag --sort=-creatordate -l '*release-*'|head -n 1 |tee ../checker/current-release.txt
          cd ../checker
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Output debug info
        run: |
          echo File list:
          ls
          echo Changed files list:
          git status --porcelain
          echo current-release.txt:
          cat current-release.txt
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Update check pipeline'
          git config --global user.email 'notepass@proton.me'
          git commit -am "Updating latest detected release version to $(cat current-release.txt)"
          git add -A
          git push