name: test-release
run-name: Checking if there is a new hadoop release
on:
  workflow_dispatch:
jobs:
  check-for-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create data
        run: |
          mkdir "$GITHUB_WORKSPACE/release_dir"
          echo release content > "$GITHUB_WORKSPACE/release_dir/release.txt"
      - name: Package release data
        run: |
          cd "$GITHUB_WORKSPACE"
          tar -cf "$GITHUB_WORKSPACE/release.tar" ./release_dir
      - name: Create release (gh cmd)
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        run: |
          gh release create -R notepass/hadoop-native-win-libs -n "Test Release" -t "GH CMD Test release" --verify-tag rel/release-3.3.6 "$GITHUB_WORKSPACE/release.tar"